### ISSUE TITLE
GPU models

### ISSUE THREAD

**Issue by xuhuaren** [gangadhar-p/NucleiDetectron#1]
Appreciate for your code and doc. I have two issues:
1.  When I run: chmod +x bin/nuclei/train.sh && ./bin/nuclei/train.sh -e 1_aug_gray_0_5_0 -v 1_aug_gray_0_5_0 -g 1 &. The code blocked. I just have two gpus. According to the config, should I use 8 gpus for this task?

2. Where is the training data augment processing code? I can't find relative content :)

Sorry to bother you.

**Comment by gangadhar-p** [comment]
1. You can change the GPU count to the number you have available. You should also change the GPU count in https://github.com/gangadhar-p/NucleiDetectron/blob/master/configs/nuclei/1_aug_gray_1_5_1_stage_2_v0.yaml#L7

2. Augmentation https://github.com/gangadhar-p/NucleiDetectron/blob/master/lib/datasets/nuclei/augmentation.py#L384
Minibatch augmentation call: https://github.com/gangadhar-p/NucleiDetectron/blob/master/lib/roi_data/minibatch.py#L210
